# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "your-terraform-state-bucket"
    dynamodb_table = "terraform-lock"
    encrypt        = true
    key            = "live/dev/terraform.tfstate"
    region         = "us-east-1"
  }
}
