# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
variable "infoblox_username" {
  description = "Username for Infoblox NIOS"
  type        = string
  sensitive   = true
}

variable "infoblox_password" {
  description = "Password for Infoblox NIOS"
  type        = string
  sensitive   = true
}

variable "infoblox_server" {
  description = "Infoblox NIOS server hostname or IP"
  type        = string
}

variable "infoblox_ssl_verify" {
  description = "SSL verification mode for Infoblox connection"
  type        = bool
  default     = true
}

variable "aws_region" {
  description = "AWS region for state storage"
  type        = string
  default     = "us-east-1"
}

variable "environment" {
  description = "Environment name"
  type        = string
}

variable "project_name" {
  description = "Project name"
  type        = string
  default     = "infoblox-automation"
}
